name: dashboard frontend

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: welcome message
        run: echo "Welcome to Github Actions for the First Time"
      
      
