name: dashboard frontend

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: verify node version
        run: node -v

      - name: verify npm version
        run: npm -v

      - name: install dependencies
        run: npm install

      - name: build react application
        run: CI=false npm run build

      - name: show build folder
        run: ls -al build
      
        
